site_name: ImageTiler
site_url: "https://dytme.github.io/ImageTiler/"

theme:
  name: material
  logo: image_tiler_logo.svg
  favicon: image_tiler_logo.svg
  palette:
    # Primary is the header and sidebar background
    primary: light blue
    # Accent is for links, buttons, and hover states
    accent: blue grey
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.highlight
    - content.code.annotate
    - navigation.top
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list

copyright: MIT Licence.

plugins:
  - search
  - offline

nav:
  - Getting Started: index.md
  - Tiling Modes: tilingmodes.md
  - Reference: api.md
  - Example Sketches: examples.md
